---

# SSH client settings
# Allow ssh _client_ to use password login. This is necessary for password
# login to from a Guacamole SSH connection.
ssh_client_password_login: yes

# Pip packages
pip_install_packages:
  - docker
  - docker-compose

# Docker users
docker_users:
  - "{{ ansible_user }}"

# Docker compose variables
guacamole_home_container: /guacamole_home
guacamole_home_host: "{{ home_dir }}/guacamole_home"
guacamole_extensions_dir: "{{ guacamole_home_host }}/extensions"
guac_db_name: guacamole
guac_db_user: guacamole
guac_version: "1.4.0"
postgres_version: 13-alpine  # version > 13 appear not to work
init_db_file_path: "{{ home_dir }}/initdb.sql"
postgres_volume: "{{ home_dir }}/postgres"
openldap_version: "2.5"
openldap_volume: "{{ home_dir }}/openldap"
schema_directory: "{{ home_dir }}/ldifs"
guac_schema_file_path: "{{ schema_directory }}/guacConfigGroup.lidf"
self_service_password_version: "1.4.3"
self_service_password_config_path: "{{ home_dir }}/ssp_conf.php"
traefik_dynamic_config: "{{ home_dir }}/dynamic_conf.yml"
traefik_version: v2.7
traefik_acme_volume: "{{ home_dir }}/acme"

# Guacamole parameters
guacamole_port: 8080
guacamole_root: http://localhost:{{ guacamole_port }}/guacamole

# LDAP parameters
ldap_uri: ldap://localhost:{{ ldap_port }}
