---

# SSH client settings
# Allow ssh _client_ to use password login. This is necessary for password
# login to from a Guacamole SSH connection.
ssh_client_password_login: yes

# Pip packages
pip_install_packages:
  - docker
  - docker-compose

# Docker users
docker_users:
  - "{{ ansible_user }}"

# Docker compose variables
guacamole_home_container: /guacamole_home
guacamole_home_host: "{{ ansible_user_dir }}/guacamole_home"
guacamole_extensions_dir: "{{ guacamole_home_host }}/extensions"
guac_db_name: guacamole
guac_db_user: guacamole
guac_version: "1.4.0"
postgres_version: 13-alpine  # version > 13 appear not to work
init_db_file_path: "{{ ansible_user_dir }}/initdb.sql"
postgres_volume: "{{ ansible_user_dir }}/postgres"
openldap_version: "2.5"
openldap_volume: "{{ ansible_user_dir }}/openldap"
schema_directory: "{{ ansible_user_dir }}/ldifs"
guac_schema_file_path: "{{ schema_directory }}/guacConfigGroup.lidf"
# self_service_password_version: "1.4.3"
traefik_dynamic_config: "{{ ansible_user_dir }}/dynamic_conf.yml"
traefik_version: v2.7
traefik_acme_volume: "{{ ansible_user_dir }}/acme"

# Guacamole route
guacamole_root: http://localhost:8080/guacamole

# Guacamole connections
guac_connections:
  - identifier: 1
    params:
      name: DSVM RDP
      parentIdentifier: ROOT
      protocol: rdp
      parameters:
        hostname: "{{ dsvm_private_ip }}"
        port: "3389"
        security: Any
        ignore-cert: "true"
        server-layout: en-gb-qwerty
        timezone: Etc/GMT+0
      attributes:
        max-connections:
        max-connections-per-user:
        weight:
        failover-only:
        guacd-port:
        guacd-encryption:
        guacd-hostname:
  - identifier: 2
    params:
      name: DSVM SSH
      parentIdentifier: ROOT
      protocol: ssh
      parameters:
        hostname: "{{ dsvm_private_ip }}"
      attributes:
        max-connections:
        max-connections-per-user:
        weight:
        failover-only:
        guacd-port:
        guacd-encryption:
        guacd-hostname:
