---

- name: Ensure system singularity is not installed
  ansible.builtin.apt:
    name: singularity-container
    state: absent

- name: Check installed version of singularity
  # This will return a non-zero return code if
  # 1. Singularity is not installed
  # 2. The singularity version does not match the variable singularity_version
  ansible.builtin.shell:
    cmd: "singularity --version | grep {{ singularity_version }}"
  changed_when: false
  failed_when: false
  register: version_check

- name: Install singularity from source
  # available debs are quite out of date
  block:
    - name: Install singularity build dependencies
      ansible.builtin.apt:
        name:
          - build-essential
          - uuid-dev
          - libgpgme-dev
          - squashfs-tools
          - libseccomp-dev
          - pkg-config
          - cryptsetup-bin
          - golang

    - name: Get singularity release
      ansible.builtin.get_url:
        url: "https://github.com/hpcng/singularity/releases/download/v{{ singularity_version }}/singularity-{{ singularity_version }}.tar.gz"
        dest: "{{ ansible_user_dir }}"
        checksum: "sha256:https://github.com/hpcng/singularity/releases/download/v{{ singularity_version }}/sha256sums"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      register: singularity_archive

    - name: Unarchive singularity source
      ansible.builtin.unarchive:
        src: "{{ singularity_archive.dest }}"
        remote_src: yes
        dest: "{{ ansible_user_dir }}"

    - name: Generate Makefile
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/singularity-{{ singularity_version }}"
        cmd: ./mconfig
        creates: "{{ ansible_user_dir }}/singularity-{{ singularity_version }}/builddir/Makefile"

    - name: Build singularity
      community.general.make:
        chdir: "{{ ansible_user_dir }}/singularity-{{ singularity_version }}/builddir"
        target: all

    - name: Install singularity
      community.general.make:
        chdir: "{{ ansible_user_dir }}/singularity-{{ singularity_version }}/builddir"
        target: install

    - name: Remove build directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/singularity-{{ singularity_version }}"
        state: absent

    - name: Remove archive
      ansible.builtin.file:
        path: "{{ singularity_archive.dest }}"
        state: absent
  when: version_check.rc != 0
