---

- name: Install xrdp
  ansible.builtin.apt:
    name: "{{ apt_packages_xrdp }}"
    state: present

- name: Set xrdp encryption level to high
  ansible.builtin.lineinfile:
    path: /etc/xrdp/xrdp.ini
    state: present
    regexp: '^(.*)encrypt_level=.*$'
    line: '\1encrypt_level=high'
    backrefs: yes
    backup: yes
  notify: Restart xrdp

- name: Write startwm.sh script
  # xrdp runs this script after starting the display server. By default
  # it starts a window manager using /etc/X11/xinitrc or ~/.xinitrc. We
  # edit this script to prevent users overriding the XFCE desktop.
  ansible.builtin.copy:
    dest: /etc/xrdp/startwm.sh
    owner: root
    group: root
    mode: 0755
    content: |
      #!/bin/sh
      if [ -r /etc/profile ]; then
          . /etc/profile
      fi

      if [ -r /etc/default/locale ]; then
          . /etc/default/locale
          export LANG LANGUAGE
      fi
      # Start xfce4
      startxfce4
    backup: yes
  notify: Restart xrdp

- name: Ensure xrdp user is in the ssl-cert group
  # This is required to let xrdp access
  # `/etc/ssl/private/ssl-cert-snakeoil.key` which is symlinked to
  # `/etc/xrdp/key.pem`
  ansible.builtin.user:
    name: xrdp
    groups: ssl-cert
    append: yes
  notify: Restart xrdp

- name: Start and enable xrdp service
  ansible.builtin.systemd:
    name: xrdp
    state: started
    enabled: yes
