---

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        # TLS 1.3 ciphers
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        # TLS 1.2 ciphers
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      preferServerCipherSuites: true
      sniStrict: true
http:
  middlewares:
    hsts-headers:
      headers:
        stsSeconds: 31536000
        forceSTSHeader: true
        stsPreload: true
        stsIncludeSubdomains: true
