---

- name: Create RDP connection
  community.general.ldap_entry:
    server_uri: "{{ ldap_uri }}"
    bind_dn: "{{ ldap_admin_dn }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn=RDP Connection,ou=groups,{{ ldap_base_dn }}"
    objectClass:
      - guacConfigGroup
      - groupOfNames
    attributes:
      cn: Desktop
      guacConfigProtocol: rdp
      guacConfigParameter:
        - hostname="{{ dsvm_private_ip }}"
        - port=3389
        - security=Any
        - ignore-cert=true
        - server-layout=en-gb-qwerty
        - timezone=Etc/GMT+0
      member: ''

- name: Create SSH connection
  community.general.ldap_entry:
    server_uri: "{{ ldap_uri }}"
    bind_dn: "{{ ldap_admin_dn }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn=SSH Connection,ou=groups,{{ ldap_base_dn }}"
    objectClass:
      - guacConfigGroup
      - groupOfNames
    attributes:
      cn: Command Line
      guacConfigProtocol: ssh
      guacConfigParameter:
        - hostname="{{ dsvm_private_ip }}"
      member: ''
