---

- name: Check all required variables are defined
  hosts: localhost

  vars_files:
    - vars/ansible_vars.yaml

  tasks:
    - name: Check all required variables are defined
      ansible.builtin.assert:
        that: item is defined
        success_msg: "Required variable {{ item }} is defined"
        fail_msg: "Required variable {{ item }} is not defined!"
      loop:
        - guac_db_password
        - guac_admin_password


- name: Basic hardening for all hosts
  hosts: all
  become: yes
  tags: hardening

  collections:
    - devsec.hardening

  vars_files:
    - vars/terraform_vars.yaml

  roles:
    - role: wait_for_cloud_init
    - role: apt_cache
    - role: devsec.hardening.ssh_hardening
    - role: oefenweb.fail2ban


- name: Configure Guacamole VM
  hosts: guacamole
  become: yes
  tags: guacamole

  collections:
    - community.general
    - scicore.guacamole

  vars_files:
    - vars/ansible_vars.yaml
    - vars/terraform_vars.yaml

  roles:
    - role: wait_for_cloud_init
    - role: apt_cache
    - role: geerlingguy.docker
    - role: geerlingguy.pip

  tasks:
    # Ensure ansible_user has docker-group privileges
    - name: Reset connection so that group changes take effect
      meta: reset_connection

    - name: Register guacamole admin user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
      register: user

    - name: Get guacamole admin user home directory
      ansible.builtin.set_fact:
        home_dir: "{{ user.home }}"

    - name: Install python3-ldap module
      ansible.builtin.apt:
        name: python3-ldap
        state: present

    - name: Configure and start Docker services
      anbile.builtin.import_tasks: tasks/guacamole/services.yaml

    - name: Create connections
      ansible.builtin.import_tasks: tasks/guacamole/connections.yaml

      # - name: (Temporarily) disable TOTP to allowd Guacamole configuration through the API
      #   ansible.builtin.import_tasks: tasks/guacamole/disable_guacamole_totp.yaml
      #
    - name: Configure guacadmin account
      ansible.builtin.import_tasks: tasks/guacamole/guacadmin.yaml

      # - name: Install and enable Guacamole TOTP extension
      #   ansible.builtin.import_tasks: tasks/guacamole/enable_guacamole_totp.yaml


- name: Configure DSVM
  hosts: dsvm
  become: yes
  tags: dsvm

  collections:
    - community.general

  vars_files:
    - vars/ansible_vars.yaml
    - vars/terraform_vars.yaml

  roles:
    - role: wait_for_cloud_init
    - role: apt_cache

  tasks:
    - name: Configure shared data disk and directory
      ansible.builtin.import_tasks: tasks/dsvm/shared_directory.yaml

    - name: Configure ingress and egress shares
      ansible.builtin.import_tasks: tasks/dsvm/shares.yaml

    - name: Install and configure RDP
      ansible.builtin.import_tasks: tasks/dsvm/rdp.yaml

    - name: Install and configure desktop
      ansible.builtin.import_tasks: tasks/dsvm/desktop.yaml

    - name: Install packages
      ansible.builtin.import_tasks: tasks/dsvm/packages.yaml


    - name: Set default Julia depot and pip cache directories
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        block: |
          export JULIA_DEPOT_PATH="/shared/.julia:$JULIA_DEPOT_PATH"
          export PIP_CACHE_DIR=/shared/.pip_cache

  handlers:
    - name: Restart xrdp
      ansible.builtin.systemd:
        name: xrdp
        state: restarted
