---

- name: Check all required variables are defined
  hosts: localhost

  vars_files:
    - vars/ansible_vars.yaml
    - vars/user_vars.yaml

  tasks:
    - name: Check all required user variables are defined
      ansible.builtin.assert:
        that:
          - item.username is defined
          - item.full_name is defined
          - item.surname is defined
          - item.number is defined
          - item.email is defined
        success_msg: "User {{ item.username }} has all required variables defined"
        fail_msg: "User {{ item }} does not have all required variables defined!"
      loop: "{{ users }}"

    - name: Check all required variables are defined
      ansible.builtin.assert:
        that: "{{ item }} is defined"
        success_msg: "Required variable {{ item }} is defined"
        fail_msg: "Required variable {{ item }} is not defined!"
      loop:
        - ldap_admin_password


- name: Manage LDAP users
  hosts: guacamole

  vars:
    ldap_uri: ldap://localhost:1389
    bind_dn: cn=ldapadmin,dc=mousehole,dc=com

  vars_files:
    - vars/ansible_vars.yaml
    - vars/user_vars.yaml

  tasks:
    - name: Add users
      # Will not overwrite an existing user entry
      community.general.ldap_entry:
        server_uri: "{{ ldap_uri }}"
        bind_dn: "{{ bind_dn }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "uid={{ item.username }},ou=users,dc=mousehole,dc=com"
        objectClass:
          - inetOrgPerson
          - posixAccount
          - ShadowAccount
        attributes:
          cn: "{{ item.full_name }}"
          gidNumber: "{{ item.number }}"
          homeDirectory: "/home/{{ item.username }}"
          mail: "{{ item.email }}"
          sn: "{{ item.surname }}"
          uid: "{{ item.username }}"
          uidNumber: "{{ item.number }}"
          # Generate a random, unstored password, salted and SHA1 hashed
          userPassword: "{{ lookup('password', '/dev/null' | password_hash('ldap_salted_sha1') }}"
      loop: users

    - name: Remove users
      community.general.ldap_entry:
        server_uri: "{{ ldap_uri }}"
        bind_dn: "{{ bind_dn }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "uid={{ item.username }},ou=users,dc=mousehole,dc=com"
        state: absent
