---
name: CI

on: push

jobs:
  ansible_lint:
    name: "Lint Ansible"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install ansible-lint
        run: pip install "ansible-lint[community]"

      - name: Lint Ansible
        run: ansible-lint

  yaml_lint:
    name: "Lint YAML"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yaml

  markdown_lint:
    name: "Lint Markdown"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Install mdl
        run: gem install mdl

      - name: Lint markdown
        run: mdl --style .mdl_style.rb ./

  markdown_link_check:
    name: "Check Markdown links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-verbose-mode: "yes"
          config-file: ".mlc_config.json"

  python_lint:
    name: "Lint Python"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install flake8
        run: pip install flake8

      - name: Lint
        run: flake8 --count --show-source --statistics

  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -diff

  tfsec:
    name: "Check Terraform Security"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check security
        uses: aquasecurity/tfsec-pr-commenter-action@v1.1.0
        with:
          working_directory: ./terraform
          tfsec_version: v1.13.0
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}

  docs:
    name: "Test Documentation Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build
        run: mkdocs build --strict
